monolog:
    channels: ['profiling']
    handlers:
        profiling:
            level:    debug
            type:     stream
            path:     '%kernel.logs_dir%/profiling.log'
            channels: ['profiling']
            max_files: 10

        critical:
            type:  stream
            path:  '%kernel.logs_dir%/critical.log'
            level: critical
            max_files: 10
            channels: ['!profiling']

        info:
            type:  stream
            path:  '%kernel.logs_dir%/app_info.log'
            level: info
            max_files: 10
            channels: ['!profiling']

#        profiling:
#            # log all messages (since debug is the lowest level)
#            level:    debug
#            type:     stream
#            path:     '%kernel.logs_dir%/profiling.log'
#            channels: ['profiling']
#        main:
#            type:         fingers_crossed
#            action_level: critical
#            handler:      grouped
#            channels: ['!profiling']
#        grouped:
#            type:    group
#            members: [critical, deduplicated, info]
#        critical:
#            type:  stream
#            path:  '%kernel.logs_dir%/critical.log'
#            level: critical
#            max_files: 10
#        info:
#            type:  stream
#            path:  '%kernel.logs_dir%/app_info.log'
#            level: debug
#            max_files: 10
#            channels: ['!profiling']
#        deduplicated:
#            type:    deduplication
#            time: 60
#            handler: swift
#        swift:
#            type:       swift_mailer
#            from_email: 'price-logger@mail.ru'
#            to_email:   '88billizzard@gmail.com'
#            subject:    'An Error Occurred! %%message%%'
#            level:      debug
#            formatter:  monolog.formatter.html
#            content_type: text/html