twig:
    globals:
        fos_csrf_provider: "@security.csrf.token_manager"
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    cache: false
    form_themes:
            - bootstrap_3_layout.html.twig
