error_list:
    path: /errors/
    controller: App\Controller\Admin\ErrorController::listAction

error_view:
    path: /errors/{id}/view/
    requirements:
      id: '\d+'
    controller: App\Controller\Admin\ErrorController::viewAction

error_delete:
    path: /errors/delete/
    controller: App\Controller\Admin\ErrorController::deleteAction

