host_list:
    path: /hosts/
    controller: App\Controller\Admin\HostController::listAction

host_add:
    path: /hosts/add/
    controller: App\Controller\Admin\HostController::addAction

host_edit:
    path: /hosts/{id}/edit/
    requirements:
      id: '\d+'
    controller: App\Controller\Admin\HostController::editAction

host_delete:
    path: /hosts/{id}/delete/
    requirements:
      id: '\d+'
    controller: App\Controller\Admin\HostController::deleteAction

