message_list:
    path: /messages/
    controller: App\Controller\Admin\MessageController::listAction

message_view:
    path: /messages/{id}/view/
    requirements:
      id: '\d+'
    controller: App\Controller\Admin\MessageController::viewAction

message_delete:
    path: /messages/delete/
    controller: App\Controller\Admin\MessageController::deleteAction

