tracker_list:
    path: /trackers/
    controller: App\Controller\Admin\TrackerController::listAction

tracker_add:
    path: /trackers/add/
    controller: App\Controller\Admin\TrackerController::addAction

tracker_edit:
    path: /trackers/{id}/edit/
    requirements:
      id: '\d+'
    controller: App\Controller\Admin\TrackerController::editAction

tracker_view:
    path: /trackers/{id}/view/
    requirements:
      id: '\d+'
    controller: App\Controller\Admin\TrackerController::viewAction

tracker_delete:
    path: /trackers/{id}/delete/
    requirements:
      id: '\d+'
    controller: App\Controller\Admin\TrackerController::deleteAction

