<?php
namespace App\Tests\Repository;

use App\Entity\Watcher;
use App\Repository\WatcherRepository;
use PHPUnit\Framework\TestCase;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Bundle\MakerBundle\Str;
use Symfony\Component\Console\Input\StringInput;
use Symfony\Component\Console\Tester\CommandTester;


class DataFixturesTest extends KernelTestCase
{
    private static $entityManager;

    public static function setUpBeforeClass()
    {
        $kernel = self::bootKernel();
        self::$entityManager = $kernel->getContainer()->get('doctrine')->getManager();
        self::loadFixturesWatcher();
        parent::setUpBeforeClass();
    }

    public function setUp()
    {
        parent::setUp();
    }

    private static function loadFixturesWatcher()
    {
        $watcher = new Watcher();
        $watcher->setStatus(Watcher::STATUS_NEW);
        $watcher->setPercent(10);
        $watcher->setStartPrice(200);

        $watcher2 = new Watcher();
        $watcher2->setStatus(Watcher::STATUS_SUCCESS);
        $watcher2->setPercent(15);
        $watcher2->setStartPrice(200);

        $watcher3 = new Watcher();
        $watcher3->setStatus(Watcher::STATUS_PRICE_CONFIRMED);
        $watcher3->setPercent(15);
        $watcher3->setStartPrice(200);

        self::$entityManager->persist($watcher);
        self::$entityManager->persist($watcher2);
        self::$entityManager->persist($watcher3);
        self::$entityManager->flush($watcher);
    }

    public static function tearDownAfterClass()
    {
        /** @var WatcherRepository $wr */
        $wr = self::$entityManager->getRepository(Watcher::class);
        //$wr->
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }
}