<?php
namespace App\Tests\phpunit;

use App\Entity\Host;
use App\Entity\Product;
use App\Entity\User;
use App\Entity\Watcher;
use App\Kernel;
use Doctrine\ORM\EntityManager;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;


class BaseTestCase extends WebTestCase
{
    /** @var EntityManager entityManager */
    protected static $entityManager;

    public static function getKernelClass()
    {
        return Kernel::class;
    }

    public static function setUpBeforeClass()
    {
        self::$kernel = self::bootKernel();
        self::$entityManager = self::$kernel->getContainer()->get('doctrine')->getManager();
        self::clearTables();
        static::loadFixtures();
        parent::setUpBeforeClass();
    }

    protected static function loadFixtures()
    {
    }

    public static function tearDownAfterClass()
    {
        self::clearTables();
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }

    private static function clearTables()
    {
        $sql = 'DELETE FROM watcher; DELETE FROM message; DELETE FROM price_tracker; DELETE FROM product; DELETE FROM `host`; DELETE FROM `user`;';
        $stmt = static::$entityManager->getConnection()->prepare($sql);
        $stmt->execute();
    }

    protected static function createTestUser()
    {
        $user = new User();
        $user->setEmail('test@test.com');
        $user->setRoles('ROLE_USER');
        $user->setPassword('$2y$12$A1comgHtNSnZwjz09PIWhuD2DOt2iV8rwG74pZ9t9apQzkwdpYByC');
        $user->setNickName('User_Test');
        self::$entityManager->persist($user);
        self::$entityManager->flush();
        return $user;
    }

    protected static function createAdminUser()
    {
        $user = new User();
        $user->setEmail('admin@admin.com');
        $user->setRoles('ROLE_ADMIN');
        $user->setPassword('$2y$12$A1comgHtNSnZwjz09PIWhuD2DOt2iV8rwG74pZ9t9apQzkwdpYByC');
        $user->setNickName('User_Admin');
        self::$entityManager->persist($user);
        self::$entityManager->flush();
        return $user;
    }
}