security_login:
    path: /login/
    controller: App\Controller\SecurityController::loginAction

security_registration:
    path: /registration/
    controller: App\Controller\SecurityController::registrationAction

security_logout:
    path: /logout/
    controller: App\Controller\SecurityController::logoutAction

security_confirm:
    path: /confirm/{code}/
    controller: App\Controller\SecurityController::confirmAction

security_forgot:
    path: /forgot/
    controller: App\Controller\SecurityController::forgotAction

security_change:
    path: /change/{code}/
    controller: App\Controller\SecurityController::changeAction