security_login:
    path: /login
    controller: App\Controller\SecurityController::loginAction

security_registration:
    path: /registration
    controller: App\Controller\SecurityController::registrationAction

security_logout:
    path: /logout
    controller: App\Controller\SecurityController::logoutAction
