security:
    resource: routes/security/
    type: directory
    prefix: /{_locale}
    requirements:
        _locale: '%app.locales%'
    defaults:
        _locale: '%locale%'

tracker:
    resource: routes/profile/
    type: directory
    prefix: /{_locale}/profile
    requirements:
        _locale: '%app.locales%'
    defaults:
        _locale: '%locale%'

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%/
        permanent: true

homepage:
    path: /{_locale}/
    controller: App\Controller\IndexController::indexAction
    requirements:
        _locale: '%app.locales%'
    defaults:
        template: index/index.html.twig
        _locale: '%locale%'

cron:
    resource: routes/cron/
    type: directory
    prefix: /cron/

