security:
    resource: routes/security/
    type: directory
    prefix: /{_locale}
    requirements:
        _locale: '%app.locales%'
    defaults:
        _locale: '%locale%'

tracker:
    resource: routes/profile/
    type: directory
    prefix: /{_locale}/profile
    requirements:
        _locale: '%app.locales%'
    defaults:
        _locale: '%locale%'

homepage:
    path: /{_locale}
    controller: App\Controller\IndexController::indexAction
    requirements:
        _locale: '%app.locales%'
    defaults:
        template: index/index.html.twig
        _locale: '%locale%'

#security_login:
#    path: /login
#    controller: App\Controller\SecurityController::loginAction


#path:      /blog/{page}
#    controller: App\Controller\BlogController::list
#    defaults:
#        page: 1
#    requirements:
#        page: '\d+'

#article_show:
#  path:     /articles/{_locale}/{year}/{slug}.{_format}
#  controller: App\Controller\ArticleController::show
#  defaults:
#      _format: html
#  requirements:
#      _locale:  en|fr
#      _format:  html|rss
#      year:     \d+
